platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target :ColorPicker do
    pod 'iOS-Color-Picker', path: '../'
end

target :SwiftyPicker do
    use_frameworks!
    pod 'iOS-Color-Picker', path: '../'
end
